"""
Harness setup — creates AI harness entry-point files (one-line redirects to AGENT.md).

Each generated file contains a single line: AGENT.md
Every harness reads its entry file, sees AGENT.md, and reads that.
Hard stops and constraints live in AGENT.md — no per-harness duplication.

Usage:
    python tools/setup_harness.py           # interactive
    python tools/setup_harness.py --harness codex gemini   # non-interactive
    python tools/setup_harness.py --list    # show available harnesses
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
TEMPLATES_DIR = Path(__file__).parent / "harness_templates"
AGENT_MD = REPO_ROOT / "AGENT.md"   # checked for existence only
GITIGNORE = REPO_ROOT / ".gitignore"

HARNESS_CONFIG: dict[str, dict] = {
    "claude_code": {
        "label": "Claude Code",
        "template": "claude.md.tmpl",
        "output": "CLAUDE.md",
        "note": "Claude Code reads CLAUDE.md at repo root",
    },
    "codex": {
        "label": "Codex CLI",
        "template": "codex.md.tmpl",
        "output": "AGENTS.md",
        "note": "Codex CLI reads AGENTS.md at repo root",
    },
    "gemini": {
        "label": "Gemini CLI",
        "template": "gemini.md.tmpl",
        "output": "GEMINI.md",
        "note": "Gemini CLI reads GEMINI.md via gemini-extension.json",
    },
    "opencode": {
        "label": "OpenCode",
        "template": "opencode.md.tmpl",
        "output": ".opencode/AGENTS.md",
        "note": "OpenCode reads .opencode/AGENTS.md",
    },
}

GITIGNORE_SECTION_HEADER = "# Harness entry points — generated by `make setup`"


def read_template(template_path: Path) -> str:
    """Read template content (a one-line redirect: 'AGENT.md')."""
    return template_path.read_text(encoding="utf-8")


def write_output(output_rel: str, content: str) -> Path:
    """Write rendered content to the output path, creating parent dirs as needed."""
    output_path = REPO_ROOT / output_rel
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def update_gitignore(paths: list[str], ignore: bool) -> None:
    """Add or remove harness output paths from .gitignore managed section."""
    existing = GITIGNORE.read_text(encoding="utf-8") if GITIGNORE.exists() else ""

    # Strip existing managed section
    lines = existing.splitlines()
    start_idx = next(
        (i for i, l in enumerate(lines) if l.strip() == GITIGNORE_SECTION_HEADER),
        None,
    )
    if start_idx is not None:
        # Find end of section (next blank line or EOF)
        end_idx = start_idx + 1
        while end_idx < len(lines) and lines[end_idx].strip():
            end_idx += 1
        lines = lines[:start_idx] + lines[end_idx:]

    # Rebuild section
    section_lines: list[str] = [GITIGNORE_SECTION_HEADER]
    section_lines.append("# Uncomment lines below to have each dev generate locally instead of committing.")
    for p in sorted(set(paths)):
        section_lines.append(p if ignore else f"# {p}")
    section_lines.append("")

    # Append section (with leading blank line if needed)
    base = "\n".join(lines).rstrip()
    new_content = base + ("\n\n" if base else "") + "\n".join(section_lines)
    GITIGNORE.write_text(new_content, encoding="utf-8")


def prompt_harnesses() -> list[str]:
    """Interactive harness selection (simple numbered menu)."""
    keys = list(HARNESS_CONFIG.keys())

    print("\nWhich harnesses will you use?")
    print("  (Cursor is always configured via .cursor/ — no generation needed)\n")
    for i, key in enumerate(keys, 1):
        cfg = HARNESS_CONFIG[key]
        existing = (REPO_ROOT / cfg["output"]).exists()
        marker = " [exists]" if existing else ""
        print(f"  {i}) {cfg['label']:15s}  → {cfg['output']}{marker}")
        print(f"     {cfg['note']}")
    print()

    raw = input("Enter numbers separated by spaces (or press Enter to skip): ").strip()
    if not raw:
        return []

    selected = []
    for part in raw.split():
        try:
            idx = int(part) - 1
            if 0 <= idx < len(keys):
                selected.append(keys[idx])
            else:
                print(f"  Ignored out-of-range: {part}")
        except ValueError:
            print(f"  Ignored non-numeric: {part}")
    return selected


def prompt_git_strategy(outputs: list[str]) -> bool:
    """Ask whether to commit or gitignore the generated files. Returns True = gitignore."""
    print("\nGenerated files — commit to git or gitignore?")
    print(f"  Files: {', '.join(outputs)}")
    print("  (c) commit    — teammates share the same harness config (recommended for teams)")
    print("  (g) gitignore — each developer generates locally (recommended for personal projects)")
    while True:
        choice = input("\nEnter c or g [c]: ").strip().lower() or "c"
        if choice in ("c", "g"):
            return choice == "g"
        print("  Please enter 'c' or 'g'.")


def run(harnesses: list[str], gitignore_mode: bool | None = None) -> None:
    if not AGENT_MD.exists():
        print(f"ERROR: {AGENT_MD} not found. Run this script from the repo root.", file=sys.stderr)
        sys.exit(1)

    generated_outputs: list[str] = []

    for key in harnesses:
        cfg = HARNESS_CONFIG[key]
        tmpl_path = TEMPLATES_DIR / cfg["template"]
        if not tmpl_path.exists():
            print(f"  WARNING: template not found: {tmpl_path}", file=sys.stderr)
            continue

        content = read_template(tmpl_path)
        out_path = write_output(cfg["output"], content)
        generated_outputs.append(cfg["output"])
        print(f"  Generated: {out_path.relative_to(REPO_ROOT)} (→ AGENT.md)")

    if not generated_outputs:
        print("Nothing generated.")
        return

    # Determine gitignore strategy
    do_gitignore = gitignore_mode
    if do_gitignore is None:
        do_gitignore = prompt_git_strategy(generated_outputs)

    update_gitignore(generated_outputs, ignore=do_gitignore)
    strategy = "gitignored (generate locally)" if do_gitignore else "committed (shared with team)"
    print(f"\nDone. Strategy: {strategy}")
    print(f"  .gitignore updated: {GITIGNORE.relative_to(REPO_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate AI harness entry-point files.")
    parser.add_argument("--harness", nargs="+", choices=list(HARNESS_CONFIG.keys()),
                        metavar=f"{{{','.join(HARNESS_CONFIG.keys())}}}",
                        help="Harnesses to generate (non-interactive)")
    parser.add_argument("--gitignore", action="store_true", default=None,
                        help="Gitignore generated files (non-interactive)")
    parser.add_argument("--commit", action="store_true", default=None,
                        help="Commit generated files (non-interactive)")
    parser.add_argument("--list", action="store_true", help="List available harnesses and exit")
    args = parser.parse_args()

    if args.list:
        print("Available harnesses:")
        for key, cfg in HARNESS_CONFIG.items():
            print(f"  {key:12s}  {cfg['label']:15s}  → {cfg['output']}")
        return

    # Determine gitignore mode for non-interactive use
    gitignore_mode: bool | None = None
    if args.gitignore:
        gitignore_mode = True
    elif args.commit:
        gitignore_mode = False

    if args.harness:
        run(args.harness, gitignore_mode=gitignore_mode)
    else:
        selected = prompt_harnesses()
        if selected:
            run(selected, gitignore_mode=gitignore_mode)
        else:
            print("No harnesses selected. Nothing to do.")


if __name__ == "__main__":
    main()
